[project]
name = "tdynamics"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Reiase", email = "reiase@gmail.com" }
]
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
